document.writeln('<!-- 这是公用的页脚部分 -->');
document.writeln('<div class="footer wow fadeInUp">');
document.writeln('  <div class="footer-c">');
document.writeln('      <!-- footer-left: 公司简介 -->');
document.writeln('      <div class="footer-item footer-left">');
document.writeln('          <p class="compony">简设装饰有限公司</p>');
document.writeln('          <div class="msgs-hyper">');
document.writeln('          <a href="#" class="msg qq"></a>');
document.writeln('          <a href="#" class="msg weibo"></a>');
document.writeln('          <a href="#" class="msg wechat"></a>');
document.writeln('          </div>');
document.writeln('      </div>');
document.writeln('      <!-- footer-middle: 公司地址 -->');
document.writeln('      <div class="footer-item footer-middle">');
document.writeln('          <p class="addr">地址：中国地区**分区6号写字楼888室</p>');
document.writeln('          <p class="tel">电话：688-8888-008</p>');
document.writeln('          <p class="fax">传真：000-66668888</p>');
document.writeln('      </div><!-- footer-middle -->');
document.writeln('      <!-- footer-right: 公司邮件 -->');
document.writeln('      <div class="footer-item footer-right">');
document.writeln('          <p class="postcode">邮编：100000</p>');
document.writeln('          <p class="phone">手机：186-6006-8008</p>');
document.writeln('          <p class="email">邮箱：00060008@163.com</p>');
document.writeln('      </div><!-- footer-right -->');
document.writeln('  </div>');
document.writeln('</div>');