document.writeln('  <!-- 这是所有页面的头部 -->');
document.writeln('    <div class="header">');
document.writeln('        <div class="header-c">');
document.writeln('            <div class="header-logo wow bounceInLeft">');
document.writeln('                <!-- 点击logo跳转到主页 -->');
document.writeln('                <a href="#" class="logo-hyper">简设装饰</a>');
document.writeln('            </div>');
document.writeln('            <!-- 选址导航 -->');
document.writeln('            <ul class="site-nav  wow lightSpeedIn">');
document.writeln('                <li class="site-nav-item">');
document.writeln('                    <a onclick="location.pathname=\'jianshe/index.html\'" class="item-hyper">首页</a>');
document.writeln('                </li>');
document.writeln('                <li class="site-nav-item">');
document.writeln('                    <a onclick="location.pathname=\'jianshe/pages/item/index.html\'" class="item-hyper">项目</a>');
document.writeln('                </li>');
document.writeln('                <li class="site-nav-item">');
document.writeln('                    <a onclick="location.pathname=\'jianshe/pages/product/index.html\'" class="item-hyper">产品</a>');
document.writeln('                </li>');
document.writeln('                <li class="site-nav-item">');
document.writeln('                    <a onclick="location.pathname=\'jianshe/pages/service/index.html\'" class="item-hyper">服务</a>');
document.writeln('                </li>');
document.writeln('                <li class="site-nav-item">');
document.writeln('                    <a onclick="location.pathname=\'jianshe/pages/news/index.html\'" class="item-hyper">新闻</a>');
document.writeln('                </li>');
document.writeln('                <li class="site-nav-item">');
document.writeln('                    <a onclick="location.pathname=\'jianshe/pages/about/index.html\'" class="item-hyper">关于</a>');
document.writeln('                </li>');
document.writeln('            </ul><!-- site-nav -->');
document.writeln('        </div> <!-- header-logo -->');
document.writeln('    </div><!-- header -->');
