document.writeln('<div class="header-btsp">');
document.writeln('  <div class="header-logo wow bounceInLeft"></div>');
document.writeln('  <div class="header-menu wow swing">');
document.writeln('      <a class="menu-btn clearfix" href="javaScript:;">');
document.writeln('          <span class="menu-line menu-top"></span>');
document.writeln('          <span class="menu-line menu-mid"></span>');
document.writeln('          <span class="menu-line menu-btm"></span>');
document.writeln('      </a>');
document.writeln('  </div>');
document.writeln('      <div class="menu-list clearfix">');
document.writeln('          <div class="menu-list-cover clearfix">');
document.writeln('              <div class="menu-item active">');
document.writeln('                  <a class="menu-hyper" href="javaScript:;">首页</a>');
document.writeln('              </div>');
document.writeln('              <div class="menu-item">');
document.writeln('                  <a class="menu-hyper" href="javaScript:;">项目</a>');
document.writeln('              </div>');
document.writeln('              <div class="menu-item">');
document.writeln('                  <a class="menu-hyper" href="javaScript:;">产品</a>');
document.writeln('              </div>');
document.writeln('              <div class="menu-item">');
document.writeln('                  <a class="menu-hyper" href="javaScript:;">服务</a>');
document.writeln('              </div>');
document.writeln('              <div class="menu-item">');
document.writeln('                  <a class="menu-hyper" href="javaScript:;">新闻</a>');
document.writeln('              </div>');
document.writeln('              <div class="menu-item">');
document.writeln('                  <a class="menu-hyper" href="javaScript:;">关于</a>');
document.writeln('              </div>');
document.writeln('          </div>');
document.writeln('      </div>');
document.writeln('</div>');
